In [22]:
import pandas as pd

# Зареждаме основните таблици
orders = pd.read_csv('../data/olist_orders_dataset.csv')
order_items = pd.read_csv('../data/olist_order_items_dataset.csv')
products = pd.read_csv('../data/olist_products_dataset.csv')
reviews = pd.read_csv('../data/olist_order_reviews_dataset.csv')
category_translation = pd.read_csv('../data/product_category_name_translation.csv')

# Бърз преглед
print("Orders shape:", orders.shape)
print("Products shape:", products.shape)
print("Reviews shape:", reviews.shape)

orders.head()

Orders shape: (99441, 8)
Products shape: (32951, 9)
Reviews shape: (99224, 7)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [23]:
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [24]:
reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [25]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [26]:
print("Общо ревюта:", len(reviews))
print("Ревюта с текст:", reviews['review_comment_message'].notna().sum())
print("Процент с текст:", round(reviews['review_comment_message'].notna().mean() * 100, 1), "%")

Общо ревюта: 99224
Ревюта с текст: 40977
Процент с текст: 41.3 %

In [27]:
# Разглеждаме преводната таблица
category_translation.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [28]:
products = products.merge(category_translation, on='product_category_name', how='left')

# Проверка - колко уникални категории имаме
print("Брой уникални категории:", products['product_category_name_english'].nunique())
products[['product_category_name', 'product_category_name_english']].head()

Брой уникални категории: 71

   product_category_name product_category_name_english
0             perfumaria                     perfumery
1                  artes                           art
2          esporte_lazer                sports_leisure
3                  bebes                          baby
4  utilidades_domesticas                    housewares

In [29]:
print("Липсващи стойности в products:")
print(products.isnull().sum())

Липсващи стойности в products:
product_id                         0
product_category_name            610
product_name_lenght              610
product_description_lenght       610
product_photos_qty               610
product_weight_g                   2
product_length_cm                  2
product_height_cm                  2
product_width_cm                   2
product_category_name_english    623
dtype: int64

In [30]:
print("Липсващи стойности в reviews:")
print(reviews.isnull().sum())

Липсващи стойности в reviews:
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [31]:
products_clean = products.dropna(subset=['product_category_name_english'])
print("Продукти преди почистване:", len(products))
print("Продукти след почистване:", len(products_clean))

Продукти преди почистване: 32951
Продукти след почистване: 32328

In [32]:
# Категориите в products, които ги има като текст, но нямат превод
products_with_category = products[products['product_category_name'].notna()]
missing_translation = products_with_category[products_with_category['product_category_name_english'].isna()]

print("Уникални категории без превод:")
print(missing_translation['product_category_name'].unique())
print("\nБрой продукти засегнати:", len(missing_translation))

Уникални категории без превод:
<StringArray>
['pc_gamer', 'portateis_cozinha_e_preparadores_de_alimentos']
Length: 2, dtype: str

Брой продукти засегнати: 13

In [33]:
# Свързваме order_items с products_clean, за да имаме категория на всеки поръчан продукт
order_products = order_items.merge(products_clean[['product_id', 'product_category_name_english']], 
                                     on='product_id', how='inner')

print("Редове в order_products:", len(order_products))
order_products.head()

Редове в order_products: 111023

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name_english
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,cool_stuff
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,pet_shop
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,furniture_decor
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,perfumery
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,garden_tools

In [34]:
# Свързваме order_products с reviews през order_id
product_reviews = order_products.merge(reviews[['order_id', 'review_score']], 
                                         on='order_id', how='inner')

print("Редове в product_reviews:", len(product_reviews))
product_reviews.head()

Редове в product_reviews: 110750

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,product_category_name_english,review_score
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,cool_stuff,5
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,pet_shop,4
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,furniture_decor,5
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,perfumery,4
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,garden_tools,5

In [35]:
category_ratings = product_reviews.groupby('product_category_name_english')['review_score'].agg(['mean', 'count'])
category_ratings = category_ratings.sort_values('mean', ascending=False)

print(category_ratings.head(10))
print("...")
print(category_ratings.tail(10))

                                           mean  count
product_category_name_english
cds_dvds_musicals                      4.642857     14
fashion_childrens_clothes              4.500000      8
books_general_interest                 4.446266    549
costruction_tools_tools                4.444444     99
flowers                                4.419355     31
books_imported                         4.400000     60
books_technical                        4.368421    266
food_drink                             4.315412    279
luggage_accessories                    4.315257   1088
small_appliances_home_oven_and_coffee  4.302632     76
...
                                       mean  count
product_category_name_english
audio                              3.825485    361
furniture_mattress_and_upholstery  3.815789     38
fashio_female_clothing             3.780000     50
party_supplies                     3.767442     43
fixed_telephony                    3.683206    262
fashion_male_clothing              3.641221    131
home_comfort_2                     3.629630     27
office_furniture                   3.493183   1687
diapers_and_hygiene                3.256410     39
security_and_services              2.500000      2

In [36]:
# Само категории с поне 30 ревюта, за да е статистически по-надеждно
reliable_ratings = category_ratings[category_ratings['count'] >= 30]
print(reliable_ratings.head(10))
print("...")
print(reliable_ratings.tail(10))

                                           mean  count
product_category_name_english
books_general_interest                 4.446266    549
costruction_tools_tools                4.444444     99
flowers                                4.419355     31
books_imported                         4.400000     60
books_technical                        4.368421    266
food_drink                             4.315412    279
luggage_accessories                    4.315257   1088
small_appliances_home_oven_and_coffee  4.302632     76
fashion_sport                          4.258065     31
fashion_shoes                          4.233716    261
...
                                       mean  count
product_category_name_english
construction_tools_safety          3.844560    193
home_confort                       3.829885    435
audio                              3.825485    361
furniture_mattress_and_upholstery  3.815789     38
fashio_female_clothing             3.780000     50
party_supplies                     3.767442     43
fixed_telephony                    3.683206    262
fashion_male_clothing              3.641221    131
office_furniture                   3.493183   1687
diapers_and_hygiene                3.256410     39

In [37]:
# Взимаме уникален списък от продукти с категория (не искаме дубликати от order_products)
unique_products = products_clean[['product_id', 'product_category_name_english']].drop_duplicates()

print("Уникални продукти:", len(unique_products))
unique_products.head()

Уникални продукти: 32328

                         product_id product_category_name_english
0  1e9e8ef04dbcff4541ed26657ea517e5                     perfumery
1  3aa071139cb16b67ca9e5dea641aaa2f                           art
2  96bd76ec8810374ed1b65e291975717f                sports_leisure
3  cef67bcfe19066a932b7673e239eb23d                          baby
4  9dc1a7de274444849c219cff195d0b71                    housewares

In [38]:
category_encoded = pd.get_dummies(unique_products['product_category_name_english'])

print("Форма на матрицата:", category_encoded.shape)
category_encoded.head()

Форма на матрицата: (32328, 71)

,agro_industry_and_commerce,air_conditioning,art,arts_and_craftmanship,audio,auto,baby,bed_bath_table,books_general_interest,books_imported,...,security_and_services,signaling_and_security,small_appliances,small_appliances_home_oven_and_coffee,sports_leisure,stationery,tablets_printing_image,telephony,toys,watches_gifts
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
3,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [39]:
import torch

# Превръщаме True/False матрицата в PyTorch tensor от числа (0.0 / 1.0)
category_matrix = torch.tensor(category_encoded.values.astype(float), dtype=torch.float32)

print("Форма на tensor-а:", category_matrix.shape)
print("Пример - първите 5 стойности на продукт 0:", category_matrix[0][:5])

Форма на tensor-а: torch.Size([32328, 71])
Пример - първите 5 стойности на продукт 0: tensor([0., 0., 0., 0., 0.])

In [40]:
import torch.nn.functional as F

# Смятаме similarity между ВСИЧКИ двойки продукти наведнъж
similarity_matrix = F.cosine_similarity(
    category_matrix.unsqueeze(1),   # (32328, 1, 71)
    category_matrix.unsqueeze(0),   # (1, 32328, 71)
    dim=2
)

print("Форма на similarity матрицата:", similarity_matrix.shape)

RuntimeError: [enforce fail at alloc_cpu.cpp:117] data. DefaultCPUAllocator: not enough memory: you tried to allocate 296808281856 bytes.

In [ ]:
def get_similar_products(product_index, top_n=5):
    # Векторът само на избрания продукт
    target_vector = category_matrix[product_index].unsqueeze(0)  # (1, 71)
    
    # Similarity между този един продукт и ВСИЧКИ останали
    similarities = F.cosine_similarity(target_vector, category_matrix, dim=1)  # (32328,)
    
    # Топ N най-близки (без самия продукт)
    top_indices = similarities.argsort(descending=True)[1:top_n+1]
    
    return top_indices, similarities[top_indices]

# Тестваме с продукт с индекс 2 (спомни си - това беше 'sports_leisure')
indices, scores = get_similar_products(2, top_n=5)
print("Similarity стойности:", scores)
print("\nПрепоръчани продукти:")
print(unique_products.iloc[indices.numpy()])

In [ ]:
def get_similar_products(product_index, top_n=5):
    target_vector = category_matrix[product_index].unsqueeze(0)
    similarities = F.cosine_similarity(target_vector, category_matrix, dim=1)
    
    # Сортираме всички индекси по similarity
    sorted_indices = similarities.argsort(descending=True)
    
    # Изрично премахваме самия продукт по index, не по позиция
    sorted_indices = sorted_indices[sorted_indices != product_index]
    
    top_indices = sorted_indices[:top_n]
    return top_indices, similarities[top_indices]

# Тест пак
indices, scores = get_similar_products(2, top_n=5)
print("Similarity стойности:", scores)
print("\nПрепоръчани продукти:")
print(unique_products.iloc[indices.numpy()])

In [ ]:
from transformers import pipeline

sentiment_model = pipeline(
    "sentiment-analysis",
    model="nlptown/bert-base-multilingual-uncased-sentiment"
)

In [ ]:
# Тестваме с прост пример на португалски
result = sentiment_model("Recebi bem antes do prazo estipulado.")
print(result)

In [ ]:
# По-силно позитивен и по-силно негативен пример за сравнение
result_positive = sentiment_model("Produto excelente, superou minhas expectativas! Recomendo muito.")
result_negative = sentiment_model("Produto péssimo, veio quebrado e o vendedor não respondeu.")

print("Позитивен пример:", result_positive)
print("Негативен пример:", result_negative)

In [ ]:
# Взимаме само ревюта с текст (помниш ли - това бяха ~42000 от общо 99224)
reviews_with_text = reviews[reviews['review_comment_message'].notna()].copy()

# За тест - само първите 20, за да не чакаме дълго
sample_reviews = reviews_with_text.head(20)

# Прилагаме модела върху всеки текст
sample_reviews['sentiment_result'] = sample_reviews['review_comment_message'].apply(
    lambda text: sentiment_model(text[:512])[0]  # [:512] защото моделът има лимит на дължина
)

sample_reviews[['review_comment_message', 'review_score', 'sentiment_result']]

In [ ]:
# Взимаме само ревюта с текст
reviews_with_text = reviews[reviews['review_comment_message'].notna()].copy()

# За тест - само първите 20
sample_reviews = reviews_with_text.head(20)

# Прилагаме sentiment модела
sample_reviews['sentiment_result'] = sample_reviews['review_comment_message'].apply(
    lambda text: sentiment_model(text[:512])[0]
)

sample_reviews[['review_comment_message', 'review_score', 'sentiment_result']]

In [ ]:
import time

# По-голяма извадка - 200 ревюта, за да имаме статистически по-интересна картина
sample_reviews = reviews_with_text.head(200).copy()

start = time.time()
sample_reviews['sentiment_result'] = sample_reviews['review_comment_message'].apply(
    lambda text: sentiment_model(text[:512])[0]
)
elapsed = time.time() - start

print(f"Обработени 200 ревюта за {elapsed:.1f} секунди")
sample_reviews[['review_comment_message', 'review_score', 'sentiment_result']].head(10)

In [ ]:
import time

print(f"Общо ревюта за обработка: {len(reviews_with_text)}")
print("Това ще отнеме приблизително 15-20 минути, моля изчакай...")

start = time.time()
reviews_with_text['sentiment_result'] = reviews_with_text['review_comment_message'].apply(
    lambda text: sentiment_model(text[:512])[0]
)
elapsed = time.time() - start

print(f"Готово! Обработени {len(reviews_with_text)} ревюта за {elapsed/60:.1f} минути")

In [ ]:
# Разбиваме sentiment_result (dict) на две отделни колони - по-лесно за работа
reviews_with_text['predicted_label'] = reviews_with_text['sentiment_result'].apply(lambda x: x['label'])
reviews_with_text['predicted_confidence'] = reviews_with_text['sentiment_result'].apply(lambda x: x['score'])

# Запазваме резултата на диска
reviews_with_text.to_csv('../data/reviews_with_sentiment.csv', index=False)

print("Запазено успешно!")
print(reviews_with_text[['review_score', 'predicted_label', 'predicted_confidence']].head(10))

In [ ]:
# Свързваме sentiment резултатите с продукти/категории (през order_items)
sentiment_with_category = order_products.merge(
    reviews_with_text[['order_id', 'predicted_label', 'predicted_confidence']], 
    on='order_id', how='inner'
)

print("Редове:", len(sentiment_with_category))
sentiment_with_category[['product_category_name_english', 'predicted_label', 'predicted_confidence']].head()

In [ ]:
# Извличаме числото от label ("5 stars" -> 5)
sentiment_with_category['predicted_score'] = sentiment_with_category['predicted_label'].str[0].astype(int)

category_sentiment = sentiment_with_category.groupby('product_category_name_english')['predicted_score'].agg(['mean', 'count'])
category_sentiment = category_sentiment[category_sentiment['count'] >= 30].sort_values('mean')

print("Категории с най-негативен sentiment (текст):")
print(category_sentiment.head(10))

In [44]:
# Зареждаме вече обработените sentiment резултати от диска (спестява 16 минути)
reviews_with_text = pd.read_csv('../data/reviews_with_sentiment.csv')

print("Заредено успешно:", len(reviews_with_text), "редове")
reviews_with_text[['review_score', 'predicted_label', 'predicted_confidence']].head()

Заредено успешно: 40977 редове

   review_score predicted_label  predicted_confidence
0             5         3 stars              0.399876
1             5         5 stars              0.538074
2             4         3 stars              0.361089
3             4         3 stars              0.654753
4             5         4 stars              0.470945

In [46]:
sentiment_with_category = order_products.merge(
    reviews_with_text[['order_id', 'predicted_label', 'predicted_confidence']], 
    on='order_id', how='inner'
)
sentiment_with_category['predicted_score'] = sentiment_with_category['predicted_label'].str[0].astype(int)

print("sentiment_with_category възстановена:", len(sentiment_with_category))

sentiment_with_category възстановена: 46923

In [47]:
# Запазваме чист списък продукти с категория (за recommendation-a)
unique_products.to_csv('../data/products_clean.csv', index=False)

# Запазваме готовата обобщена таблица за категории по sentiment
category_sentiment_full = sentiment_with_category.groupby('product_category_name_english')['predicted_score'].agg(['mean', 'count']).reset_index()
category_sentiment_full.columns = ['category', 'avg_sentiment_score', 'review_count']
category_sentiment_full.to_csv('../data/category_sentiment_summary.csv', index=False)

# Запазваме и по звезди
category_ratings_full = product_reviews.groupby('product_category_name_english')['review_score'].agg(['mean', 'count']).reset_index()
category_ratings_full.columns = ['category', 'avg_review_score', 'order_count']
category_ratings_full.to_csv('../data/category_ratings_summary.csv', index=False)

print("Всички файлове запазени успешно!")

Всички файлове запазени успешно!

In [48]:
print(products_clean['product_id'].iloc[2])

96bd76ec8810374ed1b65e291975717f